version: '3.9'

services:

  postgres:
    image: postgres:16
    container_name: postgres-container
    environment:
      POSTGRES_DB: banco_muito_irado
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: minha-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/banco_muito_irado
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
