spring.application.name=UniespTech-luana-main

spring.datasource.url=jdbc:postgresql://localhost:5432/banco_unitech
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always
management.endpoint.health.probes.enabled=true

logging.level.org.springframework=INFO
logging.level.com.projeto.uniespTech=DEBUG

spring.flyway.enabled=false