spring.application.name=java-project

spring.datasource.url=jdbc:postgresql://localhost:5432/banco_muito_irado
spring.datasource.username=postgres
spring.datasource.password=22012006

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# configuracao do flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration