spring.application.name=UniespTech-luana-main

spring.datasource.url=jdbc:mysql://localhost:3306/banco_unitech
spring.datasource.username=root
spring.datasource.password=luaroot

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration