spring.application.name=UniespTech-luana-main

spring.datasource.url=jdbc:postgresql://localhost:5432/banco_unitech
spring.datasource.username=postgres
spring.datasource.password=1234567

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration