name: CI - UniespTech

on:
  push:
    branches: [ "main", "feat/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Baixar código
      - name: Checkout
        uses: actions/checkout@v4

      # Instalar Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # Build + Testes
      - name: Build com Maven
        run: mvn clean package
        working-directory: ./UniespTech-main

      # Salvar o .jar como artefato
      - name: Upload do JAR
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: UniespTech-main/target/*.jar